FROM python:3.11

WORKDIR /workspace

COPY requirements-train-gpu.txt /tmp/requirements-train-gpu.txt
RUN pip install --no-cache-dir -r /tmp/requirements-train-gpu.txt

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/workspace/api
