apiVersion: 1

datasources:
  - name: TrackSante Prometheus
    uid: prometheus-tracksante
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: TrackSante Postgres
    uid: postgres-tracksante
    type: postgres
    access: proxy
    url: ${GRAFANA_POSTGRES_URL}
    user: ${GRAFANA_POSTGRES_USER}
    editable: false
    jsonData:
      database: ${GRAFANA_POSTGRES_DB}
      postgresVersion: 1600
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
