ALTER TABLE optical_capture_ts1_frames
  ADD COLUMN IF NOT EXISTS sht_temp_c DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS sht_rh_percent DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS ens_iaq DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS ens_eco2_ppm DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS ens_temp_c DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS mlx_ambient_c DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS mlx_object_c DOUBLE PRECISION;
